2024-05-13 22:55:49 | INFO | controller | args: Namespace(host='0.0.0.0', port=10000, dispatch_method='shortest_queue')
2024-05-13 22:55:49 | INFO | controller | Init controller
2024-05-13 22:55:51 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m95500[0m]
2024-05-13 22:55:51 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-05-13 22:55:51 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-05-13 22:55:51 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:10000[0m (Press CTRL+C to quit)
2024-05-13 23:20:01 | ERROR | stderr | [32mINFO[0m:     Shutting down
2024-05-13 23:20:01 | ERROR | stderr | [32mINFO[0m:     Waiting for application shutdown.
2024-05-13 23:20:01 | ERROR | stderr | [32mINFO[0m:     Application shutdown complete.
2024-05-13 23:20:02 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m95500[0m]
2024-05-13 23:20:02 | ERROR | stderr | Traceback (most recent call last):
2024-05-13 23:20:02 | ERROR | stderr |   File "/Users/jeffreysherer/anaconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-05-13 23:20:02 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-05-13 23:20:02 | ERROR | stderr |   File "/Users/jeffreysherer/anaconda3/lib/python3.10/runpy.py", line 86, in _run_code
2024-05-13 23:20:02 | ERROR | stderr |     exec(code, run_globals)
2024-05-13 23:20:02 | ERROR | stderr |   File "/Users/jeffreysherer/Desktop/DissertationCode/LLaVA-Med/llava/serve/controller.py", line 298, in <module>
2024-05-13 23:20:02 | ERROR | stderr |     uvicorn.run(app, host=args.host, port=args.port, log_level="info")
2024-05-13 23:20:02 | ERROR | stderr |   File "/Users/jeffreysherer/Desktop/DissertationCode/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 575, in run
2024-05-13 23:20:02 | ERROR | stderr |     server.run()
2024-05-13 23:20:02 | ERROR | stderr |   File "/Users/jeffreysherer/Desktop/DissertationCode/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
2024-05-13 23:20:02 | ERROR | stderr |     return asyncio.run(self.serve(sockets=sockets))
2024-05-13 23:20:02 | ERROR | stderr |   File "/Users/jeffreysherer/anaconda3/lib/python3.10/asyncio/runners.py", line 44, in run
2024-05-13 23:20:02 | ERROR | stderr |     return loop.run_until_complete(main)
2024-05-13 23:20:02 | ERROR | stderr |   File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
2024-05-13 23:20:02 | ERROR | stderr |   File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
2024-05-13 23:20:02 | ERROR | stderr |   File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
2024-05-13 23:20:02 | ERROR | stderr |   File "uvloop/loop.pyx", line 555, in uvloop.loop.Loop._run
2024-05-13 23:20:02 | ERROR | stderr |   File "uvloop/loop.pyx", line 474, in uvloop.loop.Loop._on_idle
2024-05-13 23:20:02 | ERROR | stderr |   File "uvloop/cbhandles.pyx", line 83, in uvloop.loop.Handle._run
2024-05-13 23:20:02 | ERROR | stderr |   File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
2024-05-13 23:20:02 | ERROR | stderr |   File "/Users/jeffreysherer/Desktop/DissertationCode/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
2024-05-13 23:20:02 | ERROR | stderr |     with self.capture_signals():
2024-05-13 23:20:02 | ERROR | stderr |   File "/Users/jeffreysherer/anaconda3/lib/python3.10/contextlib.py", line 142, in __exit__
2024-05-13 23:20:02 | ERROR | stderr |     next(self.gen)
2024-05-13 23:20:02 | ERROR | stderr |   File "/Users/jeffreysherer/Desktop/DissertationCode/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 328, in capture_signals
2024-05-13 23:20:02 | ERROR | stderr |     signal.raise_signal(captured_signal)
2024-05-13 23:20:02 | ERROR | stderr | KeyboardInterrupt
